/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class budny_moneykeeper_cv_Recognizer */

#ifndef _Included_budny_moneykeeper_cv_Recognizer
#define _Included_budny_moneykeeper_cv_Recognizer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     budny_moneykeeper_cv_Recognizer
 * Method:    nativeInitialize
 * Signature: (Landroid/content/res/AssetManager;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_budny_moneykeeper_cv_Recognizer_nativeInitialize
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     budny_moneykeeper_cv_Recognizer
 * Method:    nativeDispose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_budny_moneykeeper_cv_Recognizer_nativeDispose
  (JNIEnv *, jobject, jlong);

/*
 * Class:     budny_moneykeeper_cv_Recognizer
 * Method:    nativeRecognize
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_budny_moneykeeper_cv_Recognizer_nativeRecognize
  (JNIEnv *, jobject, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
