/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class budny_moneykeeper_cv_Filters */

#ifndef _Included_budny_moneykeeper_cv_Filters
#define _Included_budny_moneykeeper_cv_Filters
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     budny_moneykeeper_cv_Filters
 * Method:    nativeBasicFilter
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_budny_moneykeeper_cv_Filters_nativeBasicFilter
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
