/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class budny_moneykeeper_cv_Filters */

#ifndef _Included_budny_moneykeeper_cv_Filters
#define _Included_budny_moneykeeper_cv_Filters
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     budny_moneykeeper_cv_Filters
 * Method:    nativeBasic
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_budny_moneykeeper_cv_Filters_nativeBasic
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     budny_moneykeeper_cv_Filters
 * Method:    nativeBasic2
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_budny_moneykeeper_cv_Filters_nativeBasic2
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     budny_moneykeeper_cv_Filters
 * Method:    nativeHighlight
 * Signature: (JJII)Z
 */
JNIEXPORT jboolean JNICALL Java_budny_moneykeeper_cv_Filters_nativeHighlight
  (JNIEnv *, jclass, jlong, jlong, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
