/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class budny_moneykeeper_cv_Operations */

#ifndef _Included_budny_moneykeeper_cv_Operations
#define _Included_budny_moneykeeper_cv_Operations
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     budny_moneykeeper_cv_Operations
 * Method:    nativeSliceCentered
 * Signature: (JJII)Z
 */
JNIEXPORT jboolean JNICALL Java_budny_moneykeeper_cv_Operations_nativeSliceCentered
  (JNIEnv *, jclass, jlong, jlong, jint, jint);

/*
 * Class:     budny_moneykeeper_cv_Operations
 * Method:    nativeMergeCentered
 * Signature: (JJJ)Z
 */
JNIEXPORT jboolean JNICALL Java_budny_moneykeeper_cv_Operations_nativeMergeCentered
  (JNIEnv *, jclass, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
